server:
  port: 9000

spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: user_route
              uri: http://localhost:9045
              predicates:
                - Path=/api/usr/**
              filters:
                - RewritePath=/api/usr(?<segment>/?.*), /user${segment}
            - id: job_route
              uri: http://localhost:9055
              predicates:
                - Path=/api/job/**
              filters:
                - RewritePath=/api/job(?<segment>/?.*), /job${segment}

management:
  endpoints:
    web:
      exposure:
        include: health,info

info:
  application:
    name: Api Gateway
    description: Openjob Api Gateway
    version: 0.0.1-SNAPSHOT