server:
  port: 9000
spring:
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: http://localhost:8080  # Modifica con l'URI corretto
          predicates:
            - Path=/user/**