server:
  port: 9001

# Gateway configuration
spring:
  cloud:
    gateway:
      routes:
        - id: user_route
          uri: lb://user-microservice
          predicates:
            - Path=/api/usr/**
          filters:
            - RewritePath=/api/usr/(?<segment>.*), /users/${segment}
        - id: job_route
          uri: lb://job-microservice
          predicates:
            - Path=/api/job/**
          filters:
            - RewritePath=/api/job/(?<segment>.*), /${segment}

eureka:
  client:
    registerWithEureka: true
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    lease-renewal-interval-in-seconds: 30

# Spring Boot Actuator configuration
management:
  endpoints:
    web:
      exposure:
        include: health,info,refresh

# Application info
info:
  application:
    name: Api Gateway
    description: Openjob Api Gateway
    version: 0.0.1-SNAPSHOT