server:
  port: 9000
spring:
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: http://localhost:9045  # porta corretta del user-service
          predicates:
            - Path=/user/**
        - id: job-service
          uri: http://localhost:9055  # porta corretta del job-service
          predicates:
            - Path=/job/**