server:
  port: 8761

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false


management:
  endpoints:
    web:
      exposure:
        include: health,info

info:
  application:
    name: Discovery Server
    description: Openjob Discovery Server
    version: 0.0.1-SNAPSHOT

spring:
  cloud:
    config:
      enabled: false